/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
package Solutions;

public class Problem2 extends Problem{
	
	public void solve(){
		int num1 = 1;
      	int num2 = 1;
      	int accumulator = 0;
      	int lastnumber = 4000000;
      
      	while(num1 <= lastnumber)
      	{
        	num1=num1+num2;
         
         	num2=num1-num2;
         
         	if (num1 % 2 == 0)
         	{
             		accumulator = accumulator + num1;
         	}
      	}
      	
      	solution = accumulator*1.0;
      	printSolution();
	}
	
	void printSolution(){
		System.out.println(Problem2.class.getSimpleName() + " solution = " + solution);
	}
}
